### ISSUE TITLE
Can you send me the code and database to me?

### ISSUE THREAD

**Issue by rockywind** [alexander-rakhlin/Return-to-Diabetic-Retinopathy-Detection#1]
I am a graduate student from China, doing DR screening research, so I hope to be able to communicate with you later.
My E-mail is:1290890461@qq.com

Thank you very much!

**Comment by alexander-rakhlin** [comment]
The code is proprietary, but you can look at my first DRD project, it's open source. It's not powerful like this one, but based on very interesting concept. The dataset is available on Kaggle

**Comment by rockywind** [comment]
Dear friend
   I'm very pleased to receive your replay.I am doing MA detection and need to have a location labeled database such as CARA143 and HEI-MED database.I have unable to find them on line.Can you help me?
   Thank you very much!






------------------ 原始邮件 ------------------
发件人: "Alexander Rakhlin";<notifications@github.com>;
发送时间: 2017年2月26日(星期天) 晚上10:46
收件人: "alexander-rakhlin/Return-to-Diabetic-Retinopathy-Detection"<Return-to-Diabetic-Retinopathy-Detection@noreply.github.com>; 
抄送: "飞鸟无涯"<1290890461@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [alexander-rakhlin/Return-to-Diabetic-Retinopathy-Detection] Canyou send me the code and database to me? (#1)




The code is proprietary, but you can look at my first DRD project, it's open source. It's not powerful like this one, but based on very interesting concept.

**Comment by alexander-rakhlin** [comment]
I was researching only DR and can recommend Kaggle or Messidor(-2) to this end. Kaggle is the largest available on-line. As far as I understand, annotated retinal segmentation is hard to find if ever possible.

P.S. Have you looked at this?
[Advancing Bag-of-Visual-Words Representations for Lesion Classification in Retinal Images](https://figshare.com/articles/Advancing_Bag_of_Visual_Words_Representations_for_Lesion_Classification_in_Retinal_Images/953671)
