### ISSUE TITLE
Publishing source code

### ISSUE THREAD

**Issue by mikevoets** [alexander-rakhlin/Return-to-Diabetic-Retinopathy-Detection#2]
Hi Alexander!

Loved your work and your paper. Exciting to see promising results from a model that detects diabetic retinopathy. Are you planning to publish the source code some time?

**Comment by alexander-rakhlin** [comment]
Thank you. The code was developed with commercialization and further development in mind, and remains such as still. Sorry.

**Comment by mikevoets** [comment]
Understood! Could you say something about how many epochs it took for your network to converge during training?

**Comment by alexander-rakhlin** [comment]
In the order of 100-200
